apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-app
  labels:
    app: vprofile
spec:
  replicas: 3  # Adjust as needed
  selector:
    matchLabels:
      app: vprofile
  template:
    metadata:
      labels:
        app: vprofile
    spec:
      containers:
        - name: vprofile-app
          image: us-central1-docker.pkg.dev/sage-collector-447704-n9/vprofile/vprofile-app:latest  # Change if needed
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
