apiVersion: v1
kind: Service
metadata:
  name: vprofile-service
  labels:
    app: vprofile
spec:
  type: LoadBalancer  # Change to ClusterIP or NodePort if needed
  selector:
    app: vprofile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
